<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<LangVersion>preview</LangVersion>
		<NoWarn>NU1701</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.3-preview.1.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Sudoku.Graphics\Sudoku.Graphics.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_PhantomDice.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Unused\Icon_Sample.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Dice.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_I.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_I_Single.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_J.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_J_Double.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_J_Single.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_J_Triple.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_L.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_L_Double.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_L_Single.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_L_Triple.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_O.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_S.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_S_Single.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_T.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_T_Double.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_T_Single.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_T_Triple.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_Z.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Icons\Tetris_Z_Single.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Tetris.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_None.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Text_Candidate.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Text_Given.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Text_Modifiable.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\LocalizationResources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>LocalizationResources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\LocalizationResources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>LocalizationResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
