<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<LangVersion>preview</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<NoWarn>NU1701</NoWarn>
		<ApplicationIcon>Assets\icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.3-preview.1.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Sudoku.Graphics\Sudoku.Graphics.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\icon.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Candidate_Circle.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Candidate_Cross.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPairText_Arrow.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPairText_ComparisonOperator.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPairText_Number.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPairText_Raw.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPairText_RomanNumeral.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPair_Bar.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPair_BridgeLine.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPair_ConnectionLine.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPair_Kropki.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPair_KropkiSquare.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellPair_KropkiTriangle.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellText_Arrow.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellText_BorderAlignedDigit.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellText_Exclamation.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellText_Question.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellText_Suit.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_CellText_ZodiacEmoji.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_ApexCornerTriangle.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Arrow.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_ArrowTriangle.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Battenburg.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_BisectorLine.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_BorderAlignedArrow.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_BorderAlignedTriangle.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Circle.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Cross.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Diamond.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Hexagon.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_LargeDiamond.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_LoopSegmentLine.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_MoonPhase.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Polygon.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_SevenSegmentDisplay.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Square.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Surrounding_Triangles.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_PhantomDice.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Triangle.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Dice.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Cell_Tetromino.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_None.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Text_Candidate.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Text_Given.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\ToolItems\ToolItem_Text_Modifiable.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Unused\Icon_Sample.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\LocalizationResources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>LocalizationResources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\LocalizationResources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>LocalizationResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
