//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Graphics.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Graphics.UI.Properties.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,;，；、.
        /// </summary>
        public static string _ValidSeparators {
            get {
                return ResourceManager.GetString("_ValidSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AboutWindow_Author {
            get {
                return ResourceManager.GetString("AboutWindow_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyouyama Kazusa.
        /// </summary>
        public static string AboutWindow_AuthorName {
            get {
                return ResourceManager.GetString("AboutWindow_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili:.
        /// </summary>
        public static string AboutWindow_Bilibili {
            get {
                return ResourceManager.GetString("AboutWindow_Bilibili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://space.bilibili.com/23736703.
        /// </summary>
        public static string AboutWindow_BilibiliPage {
            get {
                return ResourceManager.GetString("AboutWindow_BilibiliPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string AboutWindow_ClickMe {
            get {
                return ResourceManager.GetString("AboutWindow_ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub:.
        /// </summary>
        public static string AboutWindow_GitHub {
            get {
                return ResourceManager.GetString("AboutWindow_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/kyoyama-kazusa.
        /// </summary>
        public static string AboutWindow_GitHubPage {
            get {
                return ResourceManager.GetString("AboutWindow_GitHubPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearCell {
            get {
                return ResourceManager.GetString("ClearCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CreateNewCanvasWindow_Cancel {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell size.
        /// </summary>
        public static string CreateNewCanvasWindow_CellSize {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_CellSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateNewCanvasWindow_Create {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Template.
        /// </summary>
        public static string CreateNewCanvasWindow_DefaultTemplate {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_DefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat border as thick lines.
        /// </summary>
        public static string CreateNewCanvasWindow_DrawBordersAsThickLines {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_DrawBordersAsThickLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable rounded rectangle.
        /// </summary>
        public static string CreateNewCanvasWindow_IsBorderRoundedRectangle {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_IsBorderRoundedRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of columns of column.
        /// </summary>
        public static string CreateNewCanvasWindow_NumberOfBlockColumns {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_NumberOfBlockColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rows of block.
        /// </summary>
        public static string CreateNewCanvasWindow_NumberOfBlockRows {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_NumberOfBlockRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rows and columns.
        /// </summary>
        public static string CreateNewCanvasWindow_NumberOfRowsAndColumns {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_NumberOfRowsAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin of rendered grid (pixels).
        /// </summary>
        public static string CreateNewCanvasWindow_RenderedGridMargin {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_RenderedGridMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Template.
        /// </summary>
        public static string CreateNewCanvasWindow_StandardTemplate {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_StandardTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new canvas.
        /// </summary>
        public static string CreateNewCanvasWindow_Title {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reserved outside lines.
        /// </summary>
        public static string CreateNewCanvasWindow_Vector {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_Vector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string CreateNewCanvasWindow_VectorBottom {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_VectorBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string CreateNewCanvasWindow_VectorLeft {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_VectorLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string CreateNewCanvasWindow_VectorRight {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_VectorRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string CreateNewCanvasWindow_VectorTop {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_VectorTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string ItemType_Candidate_Circle {
            get {
                return ResourceManager.GetString("ItemType_Candidate_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross.
        /// </summary>
        public static string ItemType_Candidate_Cross {
            get {
                return ResourceManager.GetString("ItemType_Candidate_Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle (Corner).
        /// </summary>
        public static string ItemType_Cell_ApexCornerTriangle {
            get {
                return ResourceManager.GetString("ItemType_Cell_ApexCornerTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        public static string ItemType_Cell_Arrow {
            get {
                return ResourceManager.GetString("ItemType_Cell_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle (Arrow).
        /// </summary>
        public static string ItemType_Cell_ArrowTriangle {
            get {
                return ResourceManager.GetString("ItemType_Cell_ArrowTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battenburg.
        /// </summary>
        public static string ItemType_Cell_Battenburg {
            get {
                return ResourceManager.GetString("ItemType_Cell_Battenburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisector.
        /// </summary>
        public static string ItemType_Cell_BisectorLine {
            get {
                return ResourceManager.GetString("ItemType_Cell_BisectorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow (Border-aligned).
        /// </summary>
        public static string ItemType_Cell_BorderAlignedArrow {
            get {
                return ResourceManager.GetString("ItemType_Cell_BorderAlignedArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle (Border-aligned).
        /// </summary>
        public static string ItemType_Cell_BorderAlignedTriangle {
            get {
                return ResourceManager.GetString("ItemType_Cell_BorderAlignedTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string ItemType_Cell_Circle {
            get {
                return ResourceManager.GetString("ItemType_Cell_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross.
        /// </summary>
        public static string ItemType_Cell_Cross {
            get {
                return ResourceManager.GetString("ItemType_Cell_Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        public static string ItemType_Cell_Diamond {
            get {
                return ResourceManager.GetString("ItemType_Cell_Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice (Classic).
        /// </summary>
        public static string ItemType_Cell_Dice {
            get {
                return ResourceManager.GetString("ItemType_Cell_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexagon.
        /// </summary>
        public static string ItemType_Cell_Hexagon {
            get {
                return ResourceManager.GetString("ItemType_Cell_Hexagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond (Large).
        /// </summary>
        public static string ItemType_Cell_LargeDiamond {
            get {
                return ResourceManager.GetString("ItemType_Cell_LargeDiamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop segment.
        /// </summary>
        public static string ItemType_Cell_LoopSegmentLine {
            get {
                return ResourceManager.GetString("ItemType_Cell_LoopSegmentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon phase.
        /// </summary>
        public static string ItemType_Cell_MoonPhase {
            get {
                return ResourceManager.GetString("ItemType_Cell_MoonPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice (Matrix).
        /// </summary>
        public static string ItemType_Cell_PhantomDice {
            get {
                return ResourceManager.GetString("ItemType_Cell_PhantomDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        public static string ItemType_Cell_Polygon {
            get {
                return ResourceManager.GetString("ItemType_Cell_Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED digit.
        /// </summary>
        public static string ItemType_Cell_SevenSegmentDisplay {
            get {
                return ResourceManager.GetString("ItemType_Cell_SevenSegmentDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string ItemType_Cell_Square {
            get {
                return ResourceManager.GetString("ItemType_Cell_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle group.
        /// </summary>
        public static string ItemType_Cell_SurroundingTriangles {
            get {
                return ResourceManager.GetString("ItemType_Cell_SurroundingTriangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tetromino.
        /// </summary>
        public static string ItemType_Cell_Tetromino {
            get {
                return ResourceManager.GetString("ItemType_Cell_Tetromino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        public static string ItemType_Cell_Triangle {
            get {
                return ResourceManager.GetString("ItemType_Cell_Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string ItemType_CellPair_Bar {
            get {
                return ResourceManager.GetString("ItemType_CellPair_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge.
        /// </summary>
        public static string ItemType_CellPair_BridgeLine {
            get {
                return ResourceManager.GetString("ItemType_CellPair_BridgeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        public static string ItemType_CellPairText_Arrow {
            get {
                return ResourceManager.GetString("ItemType_CellPairText_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison.
        /// </summary>
        public static string ItemType_CellPairText_ComparisonOperator {
            get {
                return ResourceManager.GetString("ItemType_CellPairText_ComparisonOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string ItemType_CellPairText_Number {
            get {
                return ResourceManager.GetString("ItemType_CellPairText_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrary text.
        /// </summary>
        public static string ItemType_CellPairText_Raw {
            get {
                return ResourceManager.GetString("ItemType_CellPairText_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roman numeral.
        /// </summary>
        public static string ItemType_CellPairText_RomanNumeral {
            get {
                return ResourceManager.GetString("ItemType_CellPairText_RomanNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        public static string ItemType_CellText_Arrow {
            get {
                return ResourceManager.GetString("ItemType_CellText_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornered digits.
        /// </summary>
        public static string ItemType_CellText_BorderAlignedDigit {
            get {
                return ResourceManager.GetString("ItemType_CellText_BorderAlignedDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclamation mark.
        /// </summary>
        public static string ItemType_CellText_Exclamation {
            get {
                return ResourceManager.GetString("ItemType_CellText_Exclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question mark.
        /// </summary>
        public static string ItemType_CellText_Question {
            get {
                return ResourceManager.GetString("ItemType_CellText_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suits.
        /// </summary>
        public static string ItemType_CellText_Suit {
            get {
                return ResourceManager.GetString("ItemType_CellText_Suit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zodiacs.
        /// </summary>
        public static string ItemType_CellText_ZodiacEmoji {
            get {
                return ResourceManager.GetString("ItemType_CellText_ZodiacEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ItemType_None {
            get {
                return ResourceManager.GetString("ItemType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates mark.
        /// </summary>
        public static string ItemType_Text_Candidate {
            get {
                return ResourceManager.GetString("ItemType_Text_Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given marks.
        /// </summary>
        public static string ItemType_Text_Given {
            get {
                return ResourceManager.GetString("ItemType_Text_Given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiable marks.
        /// </summary>
        public static string ItemType_Text_Modifiable {
            get {
                return ResourceManager.GetString("ItemType_Text_Modifiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Items.
        /// </summary>
        public static string ItemTypeGroup_Basic {
            get {
                return ResourceManager.GetString("ItemTypeGroup_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Shape Items.
        /// </summary>
        public static string ItemTypeGroup_CandidateMark_ShapeBased {
            get {
                return ResourceManager.GetString("ItemTypeGroup_CandidateMark_ShapeBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Functional Items.
        /// </summary>
        public static string ItemTypeGroup_CellMark_FunctionalBased {
            get {
                return ResourceManager.GetString("ItemTypeGroup_CellMark_FunctionalBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Shape Items.
        /// </summary>
        public static string ItemTypeGroup_CellMark_ShapeBased {
            get {
                return ResourceManager.GetString("ItemTypeGroup_CellMark_ShapeBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Text Items.
        /// </summary>
        public static string ItemTypeGroup_CellMark_TextIcon {
            get {
                return ResourceManager.GetString("ItemTypeGroup_CellMark_TextIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Pair Items.
        /// </summary>
        public static string ItemTypeGroup_CellPair_Icon {
            get {
                return ResourceManager.GetString("ItemTypeGroup_CellPair_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input any text:.
        /// </summary>
        public static string MainWindow_CellPairArbitraryText {
            get {
                return ResourceManager.GetString("MainWindow_CellPairArbitraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the number of links:.
        /// </summary>
        public static string MainWindow_CellPairInputBridgeLinesCount {
            get {
                return ResourceManager.GetString("MainWindow_CellPairInputBridgeLinesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string MainWindow_CellPairNumber {
            get {
                return ResourceManager.GetString("MainWindow_CellPairNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current:.
        /// </summary>
        public static string MainWindow_CurrentMode {
            get {
                return ResourceManager.GetString("MainWindow_CurrentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_MenuItem_About {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string MainWindow_MenuItem_AboutMe {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all items.
        /// </summary>
        public static string MainWindow_MenuItem_ClearAllItems {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_ClearAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this canvas.
        /// </summary>
        public static string MainWindow_MenuItem_CloseCanvas {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_CloseCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new canvas....
        /// </summary>
        public static string MainWindow_MenuItem_CreateCanvas {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_CreateCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_MenuItem_File {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file....
        /// </summary>
        public static string MainWindow_MenuItem_LoadCanvasFromLocal {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_LoadCanvasFromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MainWindow_MenuItem_Quit {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as config to....
        /// </summary>
        public static string MainWindow_MenuItem_SaveAsConfig {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_SaveAsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save picture to....
        /// </summary>
        public static string MainWindow_MenuItem_SaveCanvas {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_SaveCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku Painter.
        /// </summary>
        public static string MainWindow_MenuItem_Title {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States (1 for on, 0 for off):.
        /// </summary>
        public static string MainWindow_PhantomDiceStatesMatrix {
            get {
                return ResourceManager.GetString("MainWindow_PhantomDiceStatesMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 1001,0110,0110,1001 (Commas may not be required).
        /// </summary>
        public static string MainWindow_PhantomDiceStatesMatrix_Example {
            get {
                return ResourceManager.GetString("MainWindow_PhantomDiceStatesMatrix_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgrid size of phantom dice dot matrix:.
        /// </summary>
        public static string MainWindow_PhantomDiceSubgridSize {
            get {
                return ResourceManager.GetString("MainWindow_PhantomDiceSubgridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is greater than {0}, which is not allowed in this program due to too large..
        /// </summary>
        public static string MessageBox_FileLengthExceeded {
            get {
                return ResourceManager.GetString("MessageBox_FileLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON File (*.json)|*.json.
        /// </summary>
        public static string OpenFileDialog_Filters_Json {
            get {
                return ResourceManager.GetString("OpenFileDialog_Filters_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load config file.
        /// </summary>
        public static string OpenFileDialog_Title_Json {
            get {
                return ResourceManager.GetString("OpenFileDialog_Title_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Files (*.png)|*.png|JPEG Files (*.jpeg;*.jpg)|*.jpeg;*.jpg|BMP Files (*.bmp)|*.bmp.
        /// </summary>
        public static string SaveFileDialog_Filters {
            get {
                return ResourceManager.GetString("SaveFileDialog_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON File (*.json)|*.json.
        /// </summary>
        public static string SaveFileDialog_Filters_Json {
            get {
                return ResourceManager.GetString("SaveFileDialog_Filters_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save canvas as picture.
        /// </summary>
        public static string SaveFileDialog_Title {
            get {
                return ResourceManager.GetString("SaveFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save canvas as config.
        /// </summary>
        public static string SaveFileDialog_Title_Json {
            get {
                return ResourceManager.GetString("SaveFileDialog_Title_Json", resourceCulture);
            }
        }
    }
}
