//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Graphics.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Graphics.UI.Properties.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AboutWindow_Author {
            get {
                return ResourceManager.GetString("AboutWindow_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyouyama Kazusa.
        /// </summary>
        public static string AboutWindow_AuthorName {
            get {
                return ResourceManager.GetString("AboutWindow_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili:.
        /// </summary>
        public static string AboutWindow_Bilibili {
            get {
                return ResourceManager.GetString("AboutWindow_Bilibili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://space.bilibili.com/23736703.
        /// </summary>
        public static string AboutWindow_BilibiliPage {
            get {
                return ResourceManager.GetString("AboutWindow_BilibiliPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string AboutWindow_ClickMe {
            get {
                return ResourceManager.GetString("AboutWindow_ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub:.
        /// </summary>
        public static string AboutWindow_GitHub {
            get {
                return ResourceManager.GetString("AboutWindow_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/kyoyama-kazusa.
        /// </summary>
        public static string AboutWindow_GitHubPage {
            get {
                return ResourceManager.GetString("AboutWindow_GitHubPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ItemType_None {
            get {
                return ResourceManager.GetString("ItemType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates mark.
        /// </summary>
        public static string ItemType_Text_Candidate {
            get {
                return ResourceManager.GetString("ItemType_Text_Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given marks.
        /// </summary>
        public static string ItemType_Text_Given {
            get {
                return ResourceManager.GetString("ItemType_Text_Given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiable marks.
        /// </summary>
        public static string ItemType_Text_Modifiable {
            get {
                return ResourceManager.GetString("ItemType_Text_Modifiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Items.
        /// </summary>
        public static string ItemTypeGroup_Basic {
            get {
                return ResourceManager.GetString("ItemTypeGroup_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current:.
        /// </summary>
        public static string MainWindow_CurrentMode {
            get {
                return ResourceManager.GetString("MainWindow_CurrentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_MenuItem_About {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string MainWindow_MenuItem_AboutMe {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this canvas.
        /// </summary>
        public static string MainWindow_MenuItem_CloseCanvas {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_CloseCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new canvas....
        /// </summary>
        public static string MainWindow_MenuItem_CreateCanvas {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_CreateCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_MenuItem_File {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MainWindow_MenuItem_Quit {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this canvas to....
        /// </summary>
        public static string MainWindow_MenuItem_SaveCanvas {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_SaveCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku Painter.
        /// </summary>
        public static string MainWindow_MenuItem_Title {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Title", resourceCulture);
            }
        }
    }
}
