//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Graphics.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Graphics.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AboutWindow_Author {
            get {
                return ResourceManager.GetString("AboutWindow_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Page.
        /// </summary>
        public static string AboutWindow_AuthorGitHub {
            get {
                return ResourceManager.GetString("AboutWindow_AuthorGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/kyoyama-kazusa.
        /// </summary>
        public static string AboutWindow_AuthorGitHubPage {
            get {
                return ResourceManager.GetString("AboutWindow_AuthorGitHubPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyouyama Kazusa.
        /// </summary>
        public static string AboutWindow_AuthorName {
            get {
                return ResourceManager.GetString("AboutWindow_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili Account.
        /// </summary>
        public static string AboutWindow_Bilibili {
            get {
                return ResourceManager.GetString("AboutWindow_Bilibili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KyouyamaKazusa (23736703).
        /// </summary>
        public static string AboutWindow_BilibiliName {
            get {
                return ResourceManager.GetString("AboutWindow_BilibiliName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click me.
        /// </summary>
        public static string AboutWindow_ClickMe {
            get {
                return ResourceManager.GetString("AboutWindow_ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of blocks (in rows and columns):.
        /// </summary>
        public static string CreateNewCanvasWindow_BlockSize {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_BlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CreateNewCanvasWindow_Cancel {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of cell (in pixels):.
        /// </summary>
        public static string CreateNewCanvasWindow_CellSize {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_CellSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows and columns of grid:.
        /// </summary>
        public static string CreateNewCanvasWindow_GridSize {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_GridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin (in pixels):.
        /// </summary>
        public static string CreateNewCanvasWindow_Margin {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create!.
        /// </summary>
        public static string CreateNewCanvasWindow_Okay {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output picture size:.
        /// </summary>
        public static string CreateNewCanvasWindow_OutputPictureSize {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_OutputPictureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin Square (No nonets).
        /// </summary>
        public static string CreateNewCanvasWindow_TabPage_LatinSquare {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_TabPage_LatinSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard (Nonets included).
        /// </summary>
        public static string CreateNewCanvasWindow_TabPage_Standard {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_TabPage_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt;.
        /// </summary>
        public static string CreateNewCanvasWindow_TargetPictureSizeStringDefaultValue {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_TargetPictureSizeStringDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new canvas....
        /// </summary>
        public static string CreateNewCanvasWindow_Title {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External size of grid (in number of rows and columns):.
        /// </summary>
        public static string CreateNewCanvasWindow_Vector {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_Vector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom:.
        /// </summary>
        public static string CreateNewCanvasWindow_VectorBottom {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_VectorBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left:.
        /// </summary>
        public static string CreateNewCanvasWindow_VectorLeft {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_VectorLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right:.
        /// </summary>
        public static string CreateNewCanvasWindow_VectorRight {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_VectorRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External size on top:.
        /// </summary>
        public static string CreateNewCanvasWindow_VectorTop {
            get {
                return ResourceManager.GetString("CreateNewCanvasWindow_VectorTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_MenuItem_About {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the current canvas.
        /// </summary>
        public static string MainWindow_MenuItem_Close {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new canvas.
        /// </summary>
        public static string MainWindow_MenuItem_Create {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_MenuItem_File {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MainWindow_MenuItem_Quit {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainWindow_MenuItem_Save {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku Graphics.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Image (*.png)|*.png|JPEG Image (*.jpg;*.jpeg)|*.jpg;*.jpeg|Bitmap Image (*.bmp)|*.bmp.
        /// </summary>
        public static string SaveFileDialog_Filters {
            get {
                return ResourceManager.GetString("SaveFileDialog_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file to....
        /// </summary>
        public static string SaveFileDialog_Title {
            get {
                return ResourceManager.GetString("SaveFileDialog_Title", resourceCulture);
            }
        }
    }
}
