//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Graphics.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Graphics.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AboutWindow_Author {
            get {
                return ResourceManager.GetString("AboutWindow_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Page.
        /// </summary>
        public static string AboutWindow_AuthorGitHub {
            get {
                return ResourceManager.GetString("AboutWindow_AuthorGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/kyoyama-kazusa.
        /// </summary>
        public static string AboutWindow_AuthorGitHubPage {
            get {
                return ResourceManager.GetString("AboutWindow_AuthorGitHubPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyouyama Kazusa.
        /// </summary>
        public static string AboutWindow_AuthorName {
            get {
                return ResourceManager.GetString("AboutWindow_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili Account.
        /// </summary>
        public static string AboutWindow_Bilibili {
            get {
                return ResourceManager.GetString("AboutWindow_Bilibili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KyouyamaKazusa (23736703).
        /// </summary>
        public static string AboutWindow_BilibiliName {
            get {
                return ResourceManager.GetString("AboutWindow_BilibiliName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click me.
        /// </summary>
        public static string AboutWindow_ClickMe {
            get {
                return ResourceManager.GetString("AboutWindow_ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_MenuItem_About {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create....
        /// </summary>
        public static string MainWindow_MenuItem_Create {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_MenuItem_File {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MainWindow_MenuItem_Quit {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku Graphics.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
    }
}
