//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big text font name.
        /// </summary>
        internal static string BigTextFontName {
            get {
                return ResourceManager.GetString("BigTextFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big text font size (scaling).
        /// </summary>
        internal static string BigTextFontSizeScale {
            get {
                return ResourceManager.GetString("BigTextFontSizeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big text font slant.
        /// </summary>
        internal static string BigTextFontSlant {
            get {
                return ResourceManager.GetString("BigTextFontSlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big text font weight.
        /// </summary>
        internal static string BigTextFontWeight {
            get {
                return ResourceManager.GetString("BigTextFontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big text font width.
        /// </summary>
        internal static string BigTextFontWidth {
            get {
                return ResourceManager.GetString("BigTextFontWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner radius of grid border.
        /// </summary>
        internal static string GridBorderRoundedRectangleCornerRadius {
            get {
                return ResourceManager.GetString("GridBorderRoundedRectangleCornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSudoku color set.
        /// </summary>
        internal static string JSudokuColorSet {
            get {
                return ResourceManager.GetString("JSudokuColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small text font name.
        /// </summary>
        internal static string SmallTextFontName {
            get {
                return ResourceManager.GetString("SmallTextFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small text font size (scaling).
        /// </summary>
        internal static string SmallTextFontSizeScale {
            get {
                return ResourceManager.GetString("SmallTextFontSizeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small text font slant.
        /// </summary>
        internal static string SmallTextFontSlant {
            get {
                return ResourceManager.GetString("SmallTextFontSlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small text font weight.
        /// </summary>
        internal static string SmallTextFontWeight {
            get {
                return ResourceManager.GetString("SmallTextFontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small text font width.
        /// </summary>
        internal static string SmallTextFontWidth {
            get {
                return ResourceManager.GetString("SmallTextFontWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates intersection color.
        /// </summary>
        internal static string TemplateIntersectionColor {
            get {
                return ResourceManager.GetString("TemplateIntersectionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color set.
        /// </summary>
        internal static string TextColorSet {
            get {
                return ResourceManager.GetString("TextColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of thick lines.
        /// </summary>
        internal static string ThickLineColor {
            get {
                return ResourceManager.GetString("ThickLineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of thick lines.
        /// </summary>
        internal static string ThickLineWidth {
            get {
                return ResourceManager.GetString("ThickLineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of thin lines.
        /// </summary>
        internal static string ThinLineColor {
            get {
                return ResourceManager.GetString("ThinLineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of thin lines.
        /// </summary>
        internal static string ThinLineWidth {
            get {
                return ResourceManager.GetString("ThinLineWidth", resourceCulture);
            }
        }
    }
}
