namespace Sudoku.Graphics;

[JsonPolymorphic(UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FailSerialization)]
[JsonDerivedType(typeof(BackgroundFillItem), nameof(BackgroundFillItem))]
[JsonDerivedType(typeof(CandidateFillItem), nameof(CandidateFillItem))]
[JsonDerivedType(typeof(CandidateTextItem), nameof(CandidateTextItem))]
[JsonDerivedType(typeof(CellApexCornerTriangleMarkItem), nameof(CellApexCornerTriangleMarkItem))]
[JsonDerivedType(typeof(CellArithmeticOperatorTextMarkItem), nameof(CellArithmeticOperatorTextMarkItem))]
[JsonDerivedType(typeof(CellArrowMarkItem), nameof(CellArrowMarkItem))]
[JsonDerivedType(typeof(CellArrowTextMarkItem), nameof(CellArrowTextMarkItem))]
[JsonDerivedType(typeof(CellArrowTriangleMarkItem), nameof(CellArrowTriangleMarkItem))]
[JsonDerivedType(typeof(CellBattenburgMarkItem), nameof(CellBattenburgMarkItem))]
[JsonDerivedType(typeof(CellBitwiseOperatorTextMarkItem), nameof(CellBitwiseOperatorTextMarkItem))]
[JsonDerivedType(typeof(CellCircleMarkItem), nameof(CellCircleMarkItem))]
[JsonDerivedType(typeof(CellComparisonOperatorTextMarkItem), nameof(CellComparisonOperatorTextMarkItem))]
[JsonDerivedType(typeof(CellCrossMarkItem), nameof(CellCrossMarkItem))]
[JsonDerivedType(typeof(CellDiamondMarkItem), nameof(CellDiamondMarkItem))]
[JsonDerivedType(typeof(CellDiceMarkItem), nameof(CellDiceMarkItem))]
[JsonDerivedType(typeof(CellEmojiMarkItem), nameof(CellEmojiMarkItem))]
[JsonDerivedType(typeof(CellExclamationMarkItem), nameof(CellExclamationMarkItem))]
[JsonDerivedType(typeof(CellFillItem), nameof(CellFillItem))]
[JsonDerivedType(typeof(CellHalveLineMarkItem), nameof(CellHalveLineMarkItem))]
[JsonDerivedType(typeof(CellHexagonMarkItem), nameof(CellHexagonMarkItem))]
[JsonDerivedType(typeof(CellMoonPhaseMarkItem), nameof(CellMoonPhaseMarkItem))]
[JsonDerivedType(typeof(CellPolygonMarkItem), nameof(CellPolygonMarkItem))]
[JsonDerivedType(typeof(CellQuestionMarkItem), nameof(CellQuestionMarkItem))]
[JsonDerivedType(typeof(CellSquareMarkItem), nameof(CellSquareMarkItem))]
[JsonDerivedType(typeof(CellSuitMarkItem), nameof(CellSuitMarkItem))]
[JsonDerivedType(typeof(CellSurroundingTrianglesMarkItem), nameof(CellSurroundingTrianglesMarkItem))]
[JsonDerivedType(typeof(CellTetrisMarkItem), nameof(CellTetrisMarkItem))]
[JsonDerivedType(typeof(CellTriangleMarkItem), nameof(CellTriangleMarkItem))]
[JsonDerivedType(typeof(CellZodiacEmojiMarkItem), nameof(CellZodiacEmojiMarkItem))]
[JsonDerivedType(typeof(GivenTextItem), nameof(GivenTextItem))]
[JsonDerivedType(typeof(ModifiableTextItem), nameof(ModifiableTextItem))]
[JsonDerivedType(typeof(TemplateLineStrokeItem), nameof(TemplateLineStrokeItem))]
public partial class Item;
